language: c

dist: bionic

services:
  - docker

os:
  - linux

script:
  - chmod -R 777 .
  - docker run -it --cap-add SYS_ADMIN --device /dev/fuse -v $PWD:/stratus -w /stratus a12e/docker-qt:5.12-gcc_64 sh build-in-docker.sh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  # upload the Docker image for CI builds triggered by tags and commits on the master branch, not PRs
  - "if [[ \"$TRAVIS_BRANCH\" == \"$TRAVIS_TAG\" || ( \"$TRAVIS_BRANCH\" == \"master\" && \"$TRAVIS_PULL_REQUEST\" == \"false\" ) ]]; then bash upload.sh Stratus-*.AppImage; fi"

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
